### ISSUE TITLE
need help for NullPointerException

### ISSUE THREAD

**Issue by venkatKrishna3110** [venkatKrishna3110/Stormy#1]
There is an exception thrown in the updateDisplay() method of the MainActivity.java Class.
@OnlySteveH has been trying to help. All inputs are welcome

**Comment by venkatKrishna3110** [comment]
issue was resolved by adding an extra line of code in grade file, which helped in better binding of the values

**Comment by OnlySteveH** [comment]
Well done on finding the solution.

**Comment by venkatKrishna3110** [comment]
Thanks a lot Steve. For all your inputs.

*Krishna* | Sr. Android Developer
Vuesol Technologies Inc.,
(980)-477-0646 | *venkatkrishna3110@gmail.com <venkatkrishna3110@gmail.com>*
